### ISSUE TITLE
Upgrade user experience and improve traceability

### ISSUE THREAD

**Issue by bdfinst** [Minimum-CD/cd-manifesto#122]
To improve the overall UX and discoverability of supporting material, I propose refactoring from the default GH Jekyll to Hugo. 

- We can also decouple the physical MVP items from the signatures while still displaying both on the main page.
  - Improves traceability of changes to core principles for ourselves and others
- We can also create a menu of sub-pages with search.

**Comment by ibathazi** [comment]
Sounds good. I was thinking of how we could break out the signatures so manifesto side is easier tracked for  meaningful changes that would solve it.
