### ISSUE TITLE
Adding reference to work in small batches

### ISSUE THREAD

**Issue by alef75** [Minimum-CD/cd-manifesto#132]
In some way, for beginner people and organizzation that come from a non agile practice /mindset, is not clear that working in small batches, (using for example user stories) is a foundation practice to get CD work.

This is also the first way of DevOps : system Thinking and flow:
without working in small batches we can't have flow, and we can't have the fully advantages of Continuous Delivery.

This misunderstanding, is something I was on, when I started our devOps / CD transformation, and is something that I still struggle to make my colleagues understand.

**Comment by alef75** [comment]
I see that references to work in small batches and commit at laest daily are in the definition of CI.
That's OK , but I think it is important to high light it in some way in the main CD definition.

**Comment by bdfinst** [comment]
We should discuss how we can document recommendations that align with the practices but in another section to keep the main page concise.

**Comment by bdfinst** [comment]
PR: https://github.com/Minimum-CD/cd-manifesto/pull/183/files
