### ISSUE TITLE
Broken link to faq subsections in the Italian translation

### ISSUE THREAD

**Issue by alef75** [Minimum-CD/cd-manifesto#148]
I'm trying to fix the broken links to the intalian faq.md subsection  in the italian readme.bd, but seem that I'm not able to find the correct path.
I've tried twice with differenth paths, but both does not work.
could some one help me please?
Thank you in advance

**Comment by bdfinst** [comment]
Let me take a look

**Comment by bdfinst** [comment]
Thisis working. https://github.com/Minimum-CD/cd-manifesto/pull/149

**Comment by bdfinst** [comment]
Merged. Working now.
