### ISSUE TITLE
[BUG] "Deploy preview" redirects to production site

### ISSUE THREAD

**Issue by JoaoGFarias** [Minimum-CD/cd-manifesto#204]
When a PR's pipeline is completed, a deploy preview link is provided (e.g. https://deploy-preview-203--minimumcd.netlify.app/, for PR #203).

However the referred link redirects to the production site (https://minimumcd.org/minimumcd/), not giving the possibility to explore the changes in the produced artifact.

**Comment by bdfinst** [comment]
This looks like an artifact of the way the site is bypassing the splash page. I'll try a few more things.

**Comment by bdfinst** [comment]
Fixed
