### ISSUE TITLE
proposed new criteria: pipelines must be deterministic

### ISSUE THREAD

**Issue by luca-ing** [Minimum-CD/cd-manifesto#258]
**Is your proposed change related to a problem? Please describe.**
I feel a criteria is missing.

If a pipeline is non-deterministic (so the same inputs don't reliably lead to the same output, i.e. the pipeline is flaky), it puts the trustworthiness of the entire pipeline and indeed the process in jeopardy.
It also undermines the power of one of the present demands: "All feature work stops when the pipeline is red". If the pipeline can go red spuriously, people will stop caring and develop alarm blindness (at best).

**Describe the solution you'd like**
For this reason, I propose the inclusion of this new MinimumCD criteria.

**Describe alternatives you've considered**
One alternative would be to simply not include it, as keeping the manifesto brief is of great value.

**Comment by bdfinst** [comment]
Sorry for the delay. Lots going on.
Would you consider determinism to be implied by:
* The pipeline decides the releasability of changes, its verdict is [definitive](https://minimumcd.org/faq/#why-should-the-pipeline-be-definitive-for-deploy)
* Artifacts created by the pipeline always meet the organization’s [definition of deployable](https://minimumcd.org/faq/#what-do-we-mean-by-definition-of-deployable)
