### ISSUE TITLE
[Question] - Should the header have consistent vertical alignment?

### ISSUE THREAD

**Issue by seanpoulter** [Minimum-CD/cd-manifesto#283]
Hi folks,

I've been reading through the website and noticed the text beside the logo in the header looks a bit low. I've added a red horizontal line to show the baseline:

>  <img width="1876" alt="Current branding text" src="https://user-images.githubusercontent.com/2585460/229620776-ffc913c7-1dfb-4137-90f3-a1fa9338b633.png">

Did you want "MinimumCD.org" to be aligned like it used to be about a year ago in June 2022 (below), and would you want a PR if you don't fix it yourself quickly? I had a look on the [Wayback Machine on archive.org](https://web.archive.org/web/20221101000000*/https://minimumcd.org/minimumcd/) to see what was intended.

> <img width="1888" alt="PixelSnap 2023-04-03 at 16 25 26@2x" src="https://user-images.githubusercontent.com/2585460/229620780-f944e76d-b243-4831-8041-68ae4858a511.png">

All the best,
Sean

**Comment by bdfinst** [comment]
I don't think any of us are fantastic with CSS, so it'd be awesome if you were open to helping out. If so, please add your name to the contributor's list as part of the PR.
