### ISSUE TITLE
npm test fails with hugo v0.111.3+extended

### ISSUE THREAD

**Issue by esmiralha** [Minimum-CD/cd-manifesto#293]
I get the following error message:

`failed to extract shortcode: shortcode "children" must be closed or self-closed`

**Comment by esmiralha** [comment]
I get the following error message:

`failed to extract shortcode: shortcode "children" must be closed or self-closed`

**Comment by seanpoulter** [comment]
I've got a fix for that locally if you haven't already solved it @bdfinst. The latest version of Hugo appears to be stricter with the linting.

**Comment by bdfinst** [comment]
Yeah, I won't get to take a look until later. If you have a fix, I'd welcome the PR.

**Comment by esmiralha** [comment]
fixed the issue title.

**Comment by seanpoulter** [comment]
Here's an example of the similar output from `npm run build`:

```
$ npm run build

> minimumcd@1.0.0 build
> hugo

Start building sites … 
hugo v0.111.3+extended darwin/amd64 BuildDate=unknown
Error: Error building site: "/Users/spoulter/Development/GitHub/seanpoulter/cd-manifesto/content/Practices/_index.md:7:1": failed to extract shortcode: shortcode "children" must be closed or self-closed
Total in 29 ms
```
