### ISSUE TITLE
[Propose Update] On the definitions of "deploy" and "release"

### ISSUE THREAD

**Issue by esmiralha** [Minimum-CD/cd-manifesto#299]
I propose adding definitions for "deploy" and "release" as tasks in the context of software development.

The manifesto is clear on the necessity of defining "deployable" and "releasable" inside an org, but the separation between the 2 actions is not clearly defined. One could assume that "deploy" means "moving into production" and "release" means "making it available for others", specially when one is not a native English speaker.

Dave Farley offers an answer here: https://www.davefarley.net/?p=333

It could serve as a starting point, maybe?

**Comment by bdfinst** [comment]
It’s been a busy couple of months. 😀 
Want to take a stab at a PR for the definitions?
