### ISSUE TITLE
Differentiate C Delivery and C Deployment?

### ISSUE THREAD

**Issue by desktophero** [Minimum-CD/cd-manifesto#45]
👋 

I am curious if the minimums around CD should include language to differentiate delivery and deployment. 

As an aspiring CI/CD practitioner, I've chosen to use a separate pipeline to help manage the flow of application code & config from the deployment code & config. Much of my experience is in large environments with many cross-team dependencies in the services space resulting in congruent constraints:

- Application code being trunk based development shouldn't care about deployment
- Business-aligned deployment doesn't map well to a pipeline - in terminology
- The separate deployment pipeline is still rooted in the same principles and practices of the application pipeline

The way I've chosen to describe this separate deployment pipeline is through a different deployment repo - a repo that addresses environment concerns, deployment strategies, and what (from the application pipeline) needs to be where (using releases).

There are plenty of pros and cons to any approach. I'm raising this issue up to see if there's an opportunity for a discussion from other others in the industry.

Thanks!

**Comment by bdfinst** [comment]
That's accurate and we discussed that during our ad how BoF sessions when we built this last week. You cannot continuously deploy to a submerged submarine because it's only in the network every 90 days or so. Not even to a Walmart store. Bandwidth budgets don't allow it.
