### ISSUE TITLE
Update upstream trunk to main

### ISSUE THREAD

**Issue by desktophero** [Minimum-CD/cd-manifesto#46]
Current trunk branch is `master`. Propose updating to `main`

**Comment by desktophero** [comment]
The default is now `main` for new repos in GitHub. The change to forks isn't overly complex and GitHub did several things to make PRs map pretty well.

https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/

**Comment by nathenharvey** [comment]
I came here to open a similar issue.  `main` is generally recognized as more inclusive than `master` and renaming the default branch on this repository would seem to be inline with the goals of creating a welcoming, inclusive, and healthy community.

I understand that consensus has already been reached but would nevertheless like to voice support for the @desktophero's initial request in an effort to appeal the decision.
