### ISSUE TITLE
Proposal: French translation 

### ISSUE THREAD

**Issue by Maeevick** [Minimum-CD/cd-manifesto#48]
# Proposal : French translation

I propose to translate the manifesto in french to contribute and diffuse it in french communities.

What do you think about it? Useless? Useful? Any impediments?

Thanks for reading ❤️

**Comment by bdfinst** [comment]
Hmmm. This is an interesting problem. 
Useless? No, even the French need CD. :)

The impediments would be keeping languages in sync as we add to things like the FAQ. Our delivery pipeline would require every language we choose to cover being translated before delivery. We'd also need to improve the tech stack from GH Pages and plain MD to something more robust that is region specific.

**Comment by ferrix** [comment]
Je crois que je suis une pomme de terre. I can buy bread from a shop but no technical skill to produce and assess the terminology in question.

**Comment by bdfinst** [comment]
I can count to 2.

**Comment by Maeevick** [comment]
I can give it a try, if you want :smile: :muscle:

**Comment by ferrix** [comment]
I'm thinking along the lines of MinimumCD.org/fr/ as the path structure and a little disclaimer that the signatories have signed the English document and that is what the community considers the root version. Maybe the signatory list could be replaced with a link to English list of signatories with the disclaimer in translated versions. 

Translations can be great when made by a community of people who know the subject deeply and understand the different connotations that exist in one language and not the other. So, if you deliberately expose your first translation to comments by people who know French, English and CD, misinterpretability will be unlikely.

Bryan wrote down the initial intentions of true or false without dependency to context etc. I think that's the best set of tests we have for translations.

I hope to see it soon in French.

**Comment by bdfinst** [comment]
This could work.

**Comment by patrickkelso** [comment]
Same. I think any translator might want to wait another week or two as we fiddle at the edges of the document before starting translations. I can work with a friend in Japan for a Japanese version.

**Comment by Jerreck** [comment]
I think after our meeting last night, it's probably safe to say that translating could proceed without expecting lots of changes in the near future.

**Comment by Halleck45** [comment]
Hi,

I've just opened https://github.com/Minimum-CD/cd-manifesto/pull/108 with french translation
